sudo: required
language: python
services:
  - docker
python:
  - "3.6"

before_install:
  # install heroku CLI.
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh
  - docker login --username=_ --password="$HEROKU_AUTH_TOKEN" registry.heroku.com

before_script:
  - docker-compose build

script:
  - docker-compose run --rm web bash -c "flake8 . &&
                                         python wait_for_postgres.py &&
                                         ./manage.py test"

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker tag web registry.heroku.com/real-world-drf-prod/web;
    docker push registry.heroku.com/real-world-drf-prod/web;
    heroku container:release web --app real-world-drf-prod;
    fi
  - if [ "$TRAVIS_BRANCH" == "qa" ]; then
    docker tag web registry.heroku.com/real-world-drf-qa/web;
    docker push registry.heroku.com/real-world-drf-qa/web;
    heroku container:release web --app real-world-drf-qa;
    fi

notifications:
  email: false

cache:
  pip: true
