site_name: backend
site_description: Example of real world project that use django rest framework
repo_url: https://github.com/cavadev/real-world-drf
site_dir: site
copyright: Copyright &copy; 2019, <a href="https://github.com/cavadev">cavadev</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
